FROM 794038219445.dkr.ecr.ap-south-1.amazonaws.com/images:20.11.1-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install --legacy-peer-deps

FROM 794038219445.dkr.ecr.ap-south-1.amazonaws.com/images:20.11.1-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY next.config.mjs ./
COPY environments/.env.development ./.env.production

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM 794038219445.dkr.ecr.ap-south-1.amazonaws.com/images:20.11.1-alpine AS runner
WORKDIR /app

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/public ./public

EXPOSE 80

ENV PORT 80

CMD ["npm", "start"]