// Mock data for Chapterwise Test (testTypeId = 4)
export const chapterwiseTestMockData = [
  {
    sectionId: 1,
    sectionName: 'Chapter 1',
    subjectDetails: {
      id: 2,
      name: 'Botany'
    },
    questions: [
      {
        questionId: 301,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'ALGAE',
        question: 'Which of the following is NOT a characteristic of algae?',
        questionImage: '#',
        option1: 'They are photosynthetic',
        option1Image: '#',
        option2: 'They have vascular tissues',
        option2Image: '#',
        option3: 'They can be unicellular or multicellular',
        option3Image: '#',
        option4: 'They are found in aquatic habitats',
        option4Image: '#',
        explanation: 'Algae do not have vascular tissues. Vascular tissues (xylem and phloem) are found in higher plants.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 20,
        paceTag: 'Good',
        status: 'correct',
        correctByPercentage: 100
      },
      {
        questionId: 302,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'ALGAE',
        question: 'Which pigment is responsible for the red color in red algae?',
        questionImage: '#',
        option1: 'Chlorophyll',
        option1Image: '#',
        option2: 'Phycoerythrin',
        option2Image: '#',
        option3: 'Fucoxanthin',
        option3Image: '#',
        option4: 'Phycocyanin',
        option4Image: '#',
        explanation: 'Phycoerythrin is the red pigment found in red algae (Rhodophyceae).',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '2',
        questionType: 0,
        selectedOption: '3',
        timeSpent: 25,
        paceTag: 'Good',
        status: 'wrong',
        correctByPercentage: 0
      },
      {
        questionId: 303,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'ALGAE',
        question: 'Which of the following is a characteristic of brown algae?',
        questionImage: '#',
        option1: 'They store food as floridean starch',
        option1Image: '#',
        option2: 'They contain phycoerythrin as a major pigment',
        option2Image: '#',
        option3: 'They store food as laminarin and mannitol',
        option3Image: '#',
        option4: 'They are primarily unicellular',
        option4Image: '#',
        explanation: 'Brown algae (Phaeophyceae) store food as complex carbohydrates in the form of laminarin and mannitol.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '2',
        questionType: 0,
        selectedOption: '',
        timeSpent: 0,
        paceTag: 'Left',
        status: 'left',
        correctByPercentage: 0
      }
    ]
  }
];

// Mock data for Concept Test (testTypeId = 5)
export const conceptTestMockData = [
  {
    sectionId: 1,
    sectionName: 'Concept 1',
    subjectDetails: {
      id: 4,
      name: 'Mathematics'
    },
    questions: [
      {
        questionId: 401,
        chapterName: 'Calculus',
        conceptName: 'Differentiation',
        question: 'What is the derivative of sin(x) with respect to x?',
        questionImage: '#',
        option1: 'cos(x)',
        option1Image: '#',
        option2: '-sin(x)',
        option2Image: '#',
        option3: 'tan(x)',
        option3Image: '#',
        option4: '-cos(x)',
        option4Image: '#',
        explanation: 'The derivative of sin(x) with respect to x is cos(x).',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '1',
        questionType: 0,
        selectedOption: '1',
        timeSpent: 15,
        paceTag: 'Good',
        status: 'correct',
        correctByPercentage: 100
      },
      {
        questionId: 402,
        chapterName: 'Calculus',
        conceptName: 'Differentiation',
        question: 'What is the derivative of e^x with respect to x?',
        questionImage: '#',
        option1: 'e^x',
        option1Image: '#',
        option2: 'xe^(x-1)',
        option2Image: '#',
        option3: 'ln(x)',
        option3Image: '#',
        option4: '1/x',
        option4Image: '#',
        explanation: 'The derivative of e^x with respect to x is e^x.',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '1',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 20,
        paceTag: 'Good',
        status: 'wrong',
        correctByPercentage: 0
      },
      {
        questionId: 403,
        chapterName: 'Calculus',
        conceptName: 'Integration',
        question: 'What is the integral of cos(x) with respect to x?',
        questionImage: '#',
        option1: 'sin(x) + C',
        option1Image: '#',
        option2: '-sin(x) + C',
        option2Image: '#',
        option3: 'tan(x) + C',
        option3Image: '#',
        option4: '-cos(x) + C',
        option4Image: '#',
        explanation: 'The integral of cos(x) with respect to x is sin(x) + C, where C is the constant of integration.',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '2',
        questionType: 0,
        selectedOption: '',
        timeSpent: 0,
        paceTag: 'Left',
        status: 'left',
        correctByPercentage: 0
      }
    ]
  }
];

// Mock data for Generate Test (testTypeId = 3)
export const generateTestMockData = [
  {
    sectionId: 0,
    sectionName: 'Physics',
    subjectDetails: {
      id: 1,
      name: 'Physics'
    },
    questions: [
      {
        questionId: 101,
        chapterName: 'Mechanics',
        conceptName: "Newton's Laws",
        question: "Which of Newton's laws states that for every action, there is an equal and opposite reaction?",
        questionImage: '#',
        option1: 'First Law',
        option1Image: '#',
        option2: 'Second Law',
        option2Image: '#',
        option3: 'Third Law',
        option3Image: '#',
        option4: 'Fourth Law',
        option4Image: '#',
        explanation: "Newton's Third Law states that for every action, there is an equal and opposite reaction.",
        explanationImage: '#',
        correctOption: '3',
        difficulty: '1',
        questionType: 0,
        selectedOption: '3',
        timeSpent: 15,
        paceTag: 'Overtime',
        status: 'correct',
        correctByPercentage: 100
      },
      {
        questionId: 102,
        chapterName: 'Thermodynamics',
        conceptName: 'Laws of Thermodynamics',
        question: 'Which law of thermodynamics states that energy cannot be created or destroyed?',
        questionImage: '#',
        option1: 'Zeroth Law',
        option1Image: '#',
        option2: 'First Law',
        option2Image: '#',
        option3: 'Second Law',
        option3Image: '#',
        option4: 'Third Law',
        option4Image: '#',
        explanation:
          'The First Law of Thermodynamics states that energy cannot be created or destroyed, only transformed from one form to another.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '1',
        timeSpent: 20,
        paceTag: 'Good',
        status: 'wrong',
        correctByPercentage: 0
      }
    ]
  },
  {
    sectionId: 0,
    sectionName: 'Chemistry',
    subjectDetails: {
      id: 3,
      name: 'Chemistry'
    },
    questions: [
      {
        questionId: 201,
        chapterName: 'Periodic Table',
        conceptName: 'Elements',
        question: 'Which element has the atomic number 6?',
        questionImage: '#',
        option1: 'Oxygen',
        option1Image: '#',
        option2: 'Carbon',
        option2Image: '#',
        option3: 'Nitrogen',
        option3Image: '#',
        option4: 'Hydrogen',
        option4Image: '#',
        explanation: 'Carbon has the atomic number 6.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 10,
        paceTag: 'Ideal',
        status: 'correct',
        correctByPercentage: 100
      },
      {
        questionId: 202,
        chapterName: 'Chemical Bonding',
        conceptName: 'Covalent Bonds',
        question: 'Which of the following is an example of a covalent bond?',
        questionImage: '#',
        option1: 'NaCl',
        option1Image: '#',
        option2: 'MgO',
        option2Image: '#',
        option3: 'H2O',
        option3Image: '#',
        option4: 'CaF2',
        option4Image: '#',
        explanation: 'H2O (water) has covalent bonds between hydrogen and oxygen atoms.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '2',
        questionType: 0,
        selectedOption: '',
        timeSpent: 0,
        paceTag: 'Left',
        status: 'left',
        correctByPercentage: 0
      }
    ]
  },
  {
    sectionId: 0,
    sectionName: 'Physics',
    subjectDetails: {
      id: 1,
      name: 'Physics'
    },
    questions: [
      {
        questionId: 103,
        chapterName: 'Optics',
        conceptName: 'Reflection',
        question: 'What is the law of reflection?',
        questionImage: '#',
        option1: 'Angle of incidence equals angle of refraction',
        option1Image: '#',
        option2: 'Angle of incidence equals angle of reflection',
        option2Image: '#',
        option3: 'Angle of reflection equals angle of refraction',
        option3Image: '#',
        option4: 'None of the above',
        option4Image: '#',
        explanation: 'The law of reflection states that the angle of incidence equals the angle of reflection.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 15,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100
      }
    ]
  }
];

export const AIM_PYT_TEST = [
  {
    sectionId: 36,
    sectionName: 'Sec-A',
    subjectDetails: {
      id: 2,
      name: 'Botany'
    },
    questions: [
      {
        questionId: 229923,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'ALGAE',
        question: 'Identify the incorrect statement w.r.t reproduction in algae.',
        questionImage: '#',
        option1: 'The algae reproduce by vegetative, asexual and sexual methods',
        option1Image: '#',
        option2: 'Vegetative reproduction is by fragmentation',
        option2Image: '#',
        option3: ' Asexual reproduction is by the production of different types of spores, the most common being the zoospores',
        option3Image: '#',
        option4: 'Zoospores are non-motile',
        option4Image: '#',
        explanation:
          '<br>\nThe algae reproduce by vegetative, asexual and sexual methods. Vegetative reproduction is by fragmentation. Each fragment develops into a thallus. Asexual reproduction is by the production of different types of spores, the most common being the zoospores. They are flagellated (motile) and on germination gives rise to new plants. Sexual reproduction takes place through fusion of two gametes.',
        explanationImage: '#',
        correctOption: '4',
        difficulty: '2',
        questionType: 0,
        selectedOption: '4',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: true
      },
      {
        questionId: 416698,
        chapterName: 'Alternating current',
        topicName: 'Instantaneous, peak, rms & average value of a.c',
        question:
          'The rms value for the saw-tooth voltage of peak value $V_0$ from $t=0$ to $t=2 \\mathrm{~T}$ as shown in figure is $\\frac{V_0}{\\sqrt{x}}.$ Find the value of $x.$ <Br> ',
        questionImage: 'img/upQus_1295916005_448891/ques4282067714.png',
        option1: '3',
        option1Image: '#',
        option2: '',
        option2Image: '#',
        option3: '',
        option3Image: '#',
        option4: '',
        option4Image: '#',
        explanation:
          '<br> General equation of $V$<br> \n$\n\\begin{aligned}\n& V=\\frac{V_0}{\\frac{T}{2}} t-V_0=\\frac{2 V_0}{T} t-V_0 \\\\\n& V_{r m s}=\\left[\\frac{\\int_\\limits 0^T V^2 d t}{T}\\right]^{\\frac{1}{2}}=\\left[\\frac{\\int_\\limits 0^T\\left(\\frac{2 V_0}{T} t-V_0\\right)^2 d t}{T}\\right]^{\\frac{1}{2}}=\\frac{V_0}{\\sqrt{3}} \\\\\n& x=3\n\\end{aligned}\n$',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '3',
        status: 'wrong',
        questionType: 1,
        previousYearName: null
      },
      {
        questionId: 343556,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'INTRODUCTION OF PLANT KINGDOM',
        question: 'Phylogenetic classification systems based on :',
        questionImage: '#',
        option1: 'Natural affinities among the organisms',
        option1Image: '#',
        option2: 'Phytochemistry',
        option2Image: '#',
        option3: 'Evolutionary relationship between the various organisms',
        option3Image: '#',
        option4: 'Reproduction',
        option4Image: '#',
        explanation: 'Evolutionary relation ship b/w the various organisms',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '1',
        questionType: 0,
        selectedOption: '3',
        timeSpent: 24,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 343561,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'BRYOPHYTA',
        question: 'Which of the following help to prevent soil erosion by forming dense mats on forest floor?',
        questionImage: '#',
        option1: 'ferns',
        option1Image: '#',
        option2: 'horsetails',
        option2Image: '#',
        option3: 'mosses',
        option3Image: '#',
        option4: 'orchids',
        option4Image: '#',
        explanation: 'Mosses prevent soil erosion by forming dense mat on the soil.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '1',
        questionType: 0,
        selectedOption: '3',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: true
      },
      {
        questionId: 343565,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'PHAEOPHYCEA',
        question:
          'In which of the following food is stored as complex carbohydrates, which may be in the form of laminarin or mannitol?',
        questionImage: '#',
        option1: 'Green alga',
        option1Image: '#',
        option2: 'Brown alga',
        option2Image: '#',
        option3: 'Red alga',
        option3Image: '#',
        option4: 'Blue-green algae',
        option4Image: '#',
        explanation:
          'In brown algae food is stored as complex carbohydrates, which may be in the form of laminarin (or) mannitol.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: true
      },
      {
        questionId: 343566,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'RHODOPHYCEA',
        question: 'Which of the following has pigments like chlorophyll a, d, and r-phycoerythrin?',
        questionImage: '#',
        option1: 'Chlorophyceae',
        option1Image: '#',
        option2: 'Phaeophyceae',
        option2Image: '#',
        option3: 'Rhodophyceae',
        option3Image: '#',
        option4: 'All of these',
        option4Image: '#',
        explanation:
          'In Rhodophyceae the major pigments are Chlorophyll-a, Chlorophyll-d and Phycoerythrin and Floridian starch is the stored food.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '1',
        questionType: 0,
        selectedOption: '3',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 343568,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'ALGAE',
        question:
          'The thallus colour of brown algae ranges from olive green to various shades of brown depending upon the abundance of',
        questionImage: '#',
        option1: 'fucoxanthin',
        option1Image: '#',
        option2: 'chlorophyll-d',
        option2Image: '#',
        option3: 'chlorophyll-b',
        option3Image: '#',
        option4: 'r-phycoerythrin',
        option4Image: '#',
        explanation:
          'Fucoxanthin is responsible for colour variation in brown algae which can vary from olive green to various shades of brown.',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '1',
        questionType: 0,
        selectedOption: '1',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: true
      },
      {
        questionId: 343579,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'GYMNOSPERM',
        question:
          'Plants in which the ovules are not enclosed by any\novary wall and remain exposed, both before and after\nfertilization?',
        questionImage: '#',
        option1: 'Pteridophytes',
        option1Image: '#',
        option2: 'Gymnosperms',
        option2Image: '#',
        option3: 'Angiosperms',
        option3Image: '#',
        option4: 'Bryophytes',
        option4Image: '#',
        explanation: 'Solution',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '2',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 229953,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'RHODOPHYCEA',
        question: 'The stored food in red algae is found in the form of',
        questionImage: '#',
        option1: 'Starch',
        option1Image: '#',
        option2: 'Mannitol',
        option2Image: '#',
        option3: 'Floridean starch',
        option3Image: '#',
        option4: 'Laminarin',
        option4Image: '#',
        explanation:
          '<br> \nThe stored food in red algae is found in the form of floridean starch. In case of brown algae it is mannitol and laminarin. In case of green algae it is starch.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '2',
        questionType: 0,
        selectedOption: '4',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'wrong',
        correctByPercentage: 0,
        bookmarkStatus: false
      },
      {
        questionId: 343563,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'INTRODUCTION OF PLANT KINGDOM',
        question: 'Chemotaxonomy based on :',
        questionImage: '#',
        option1: 'Chromosome number and structure',
        option1Image: '#',
        option2: 'Chemical constituents of the plant',
        option2Image: '#',
        option3: 'DNA characteristics',
        option3Image: '#',
        option4: 'Reproduction',
        option4Image: '#',
        explanation:
          'Chemo taxonomy (or) Chemical taxonomy is the classification of plant based on the chemical (secondary metabolites) produced by them.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '1',
        timeSpent: 24,
        paceTag: 'Too Fast',
        status: 'wrong',
        correctByPercentage: 0,
        bookmarkStatus: false
      },
      {
        questionId: 343590,
        chapterName: 'PLANT KINGDOM',
        conceptName: 'ALGAE',
        question: 'Identify the wrong statement about the following algae.\n<Br>',
        questionImage: 'img/upQus_1064356934_752896/ques455000946.png',
        option1: 'It shows oogamy with pyriform male gametes',
        option1Image: '#',
        option2: 'It has chlorophyll-a, chlorophyll-c and fucoxanthin',
        option2Image: '#',
        option3: 'Members belonging to same group have laminarin\nand mannitol as reserve food',
        option3Image: '#',
        option4: 'It has 2-8, equal and apical flagellation',
        option4Image: '#',
        explanation: 'Solution',
        explanationImage: '#',
        correctOption: '4',
        difficulty: '2',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 700,
        paceTag: 'Overtime',
        status: 'wrong',
        correctByPercentage: 0,
        bookmarkStatus: false
      }
    ]
  },
  {
    sectionId: 37,
    sectionName: 'Sec-B',
    subjectDetails: {
      id: 2,
      name: 'Botany'
    },
    questions: [
      {
        questionId: 228962,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question:
          'For more yield of recombinant protein on industrial scale __A__ were developed having capacity __B__ for culture.',
        questionImage: '#',
        option1: 'A - Incubators, B - 1000-10000 litres',
        option1Image: '#',
        option2: 'A - Bioreactors, B - 1000-10000 litres',
        option2Image: '#',
        option3: 'A - Biolistics, B - 100-10000 litres',
        option3Image: '#',
        option4: 'A - Bioreactors, B - 100-1000 litres',
        option4Image: '#',
        explanation:
          '<br> Small volume cultures cannot yield appreciable quantities of products. To produce in large quantities, the development of bioreactors, where large volumes (100-1000 litres) of culture can be processed, was required.',
        explanationImage: '#',
        correctOption: '4',
        difficulty: '2',
        questionType: 0,
        selectedOption: '4',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 229124,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'Bt toxin produced by Bacillus thuringiensis bacteria does not kill the Bacillus itself because',
        questionImage: '#',
        option1: 'The toxin is produced only after entry of Bacillus into a host after induction from host proteins',
        option1Image: '#',
        option2: 'Toxin exists as inactive protoxin in the Bacillus cell',
        option2Image: '#',
        option3: 'Activation of toxin requires acidic $\\mathrm{pH}$ which is not available in the host',
        option3Image: '#',
        option4: 'The toxin is an exo-toxin and is not stored in Bacillus cell',
        option4Image: '#',
        explanation:
          '<br> \nThe Bt toxin protein exist as inactive protoxins i.e why it does not kill the bacillus itself but once an insect ingest the inactive toxin, it is converted into an active form of toxin due to the alkaline $\\mathrm{pH}$ of the gut which solubilise the crystals.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '1',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 24,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 230276,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'Which of the following statement is not true regarding Bt-toxins?',
        questionImage: '#',
        option1: 'Bacillus thuringiensis forms protein crystals during a particular phase of their growth',
        option1Image: '#',
        option2: 'The crystals contain a toxic insecticidal protein',
        option2Image: '#',
        option3: 'Bt toxin proteins are activated in acidic pH of the insect gut which solubilize the crystals',
        option3Image: '#',
        option4:
          'The activated toxin binds to the surface of midgut epithelial cells and create pores that cause cell swelling and lysis and eventually cause death of the insect',
        option4Image: '#',
        explanation:
          '<br> Bt toxin protein exist as inactive protoxins but once an insect ingest the inactive toxin, it is converted into an active form of toxin due to the alkaline pH of the gut which solubilize the crystals.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '2',
        questionType: 0,
        selectedOption: '3',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 266843,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'The capacity to generate a whole plant from any cell of the plant is called:',
        questionImage: '#',
        option1: 'Micropropagation',
        option1Image: '#',
        option2: 'Differentiation',
        option2Image: '#',
        option3: 'Somatic hybridization',
        option3Image: '#',
        option4: 'Totipotency',
        option4Image: '#',
        explanation: '<br> Totipotency is defined as the capacity to generate a whole plant from any cell of the plant.',
        explanationImage: '#',
        correctOption: '4',
        difficulty: '2',
        questionType: 0,
        selectedOption: '4',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 50,
        bookmarkStatus: false
      },
      {
        questionId: 266883,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'Which of the following are fused in somatic hybridization involving two varieties of plants?',
        questionImage: '#',
        option1: 'Somatic embryos',
        option1Image: '#',
        option2: 'Protoplasts',
        option2Image: '#',
        option3: 'Pollens',
        option3Image: '#',
        option4: 'Callus',
        option4Image: '#',
        explanation: '<br> Protoplast of two varieties of plants are fused in somatic hybridization.',
        explanationImage: '#',
        correctOption: '2',
        difficulty: '2',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'correct',
        correctByPercentage: 100,
        bookmarkStatus: false
      },
      {
        questionId: 230266,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'Select the option which correctly matches.',
        questionImage: '#',
        option1: 'Nematode parasite - Meloidegyne incognitia',
        option1Image: '#',
        option2: 'Transgenic plant -  Agrobacterium',
        option2Image: '#',
        option3: 'ELISA - DNA polymerase',
        option3Image: '#',
        option4: 'cryIAc - Corn borer',
        option4Image: '#',
        explanation:
          '<br> Transgenic plant - Bt-Cotton <br> ELISA -  Antigen-antibody interactions <br> cryIAc -  Cotton bollworm',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '2',
        questionType: 0,
        selectedOption: '2',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'wrong',
        correctByPercentage: 0,
        bookmarkStatus: false
      },
      {
        questionId: 230290,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question:
          'Assertion (A): Specific Bt toxin genes were isolated from Bacillus thuringiensis and incorporated into the several crop plants such as cotton. <br>\nReason (R): The choice of genes depends upon the crop and the targeted pest, as most Bt toxins are not insect-group specific.',
        questionImage: '#',
        option1: 'Both Assertion (A) and Reason (R) are true, and Reason (R) is a correct explanation of Assertion (A).',
        option1Image: '#',
        option2: 'Both Assertion (A) and Reason (R) are true, and Reason (R) is not a correct explanation of Assertion (A).',
        option2Image: '#',
        option3: 'Assertion(A) is true, and Reason (R) is false.',
        option3Image: '#',
        option4: 'Assertion (A) is false, and Reason (R) is true.',
        option4Image: '#',
        explanation:
          '<br>The choice of genes depends upon the crop and the targeted pest, as most Bt toxins are insect-group specific.',
        explanationImage: '#',
        correctOption: '3',
        difficulty: '2',
        questionType: 0,
        selectedOption: '1',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'wrong',
        correctByPercentage: 0,
        bookmarkStatus: false
      },
      {
        questionId: 228963,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'Proteins produced by some strains of Bacillus thuringiensis kill all the following organisms except',
        questionImage: '#',
        option1: 'Meloidegyne',
        option1Image: '#',
        option2: 'Armyworm',
        option2Image: '#',
        option3: 'Flies',
        option3Image: '#',
        option4: 'Mosquitoes',
        option4Image: '#',
        explanation:
          '<br> Some strains of Bacillus thuringiensis produce proteins that kill certain insects such as lepidopterans (tobacco budworm, armyworm), coleopterans (beetles) and dipterans (flies, mosquitoes). It does not kill Meloidegyne.',
        explanationImage: '#',
        correctOption: '1',
        difficulty: '2',
        questionType: 0,
        selectedOption: '',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'left',
        correctByPercentage: 0,
        bookmarkStatus: true
      },
      {
        questionId: 229103,
        chapterName: 'BIOTECHNOLOGY AND ITS APPLICATIONS',
        conceptName: 'BIOTECHNOLOGICAL APPLICATIONS IN AGRICULTURE',
        question: 'Which of the following is not an use of genetic modification in transgenic plants?',
        questionImage: '#',
        option1: 'Making crops more sensitive to abiotic stresses',
        option1Image: '#',
        option2: 'Reduced reliance on chemical pesticides',
        option2Image: '#',
        option3: 'Enhanced nutritional value of food',
        option3Image: '#',
        option4: 'Increased efficiency of mineral usage by plants',
        option4Image: '#',
        explanation:
          "<br> Genetic modification has: <br>\n(I) made crops more tolerant to abiotic stresses (cold, drought, salt, heat). <br>\n(II) reduced reliance on chemical pesticides (pestresistant crops). <br> \n(III) helped to reduce post harvest losses. <br> \n(IV) increased efficiency of mineral usage by plants (this prevents early exhaustion of fertility of soil). <br> \n(V) enhanced nutritional value of food, e.g., golden rice, i.e., Vitamin 'A' enriched rice. ",
        explanationImage: '#',
        correctOption: '1',
        difficulty: '3',
        questionType: 0,
        selectedOption: '',
        timeSpent: 12,
        paceTag: 'Too Fast',
        status: 'left',
        correctByPercentage: 0,
        bookmarkStatus: true
      }
    ]
  }
];
